### PR TITLE
BP-1210 Subscription to changes on redis via ws/subscribe fails silently

### PR DESCRIPTION
**Pull request by aforechi**
close all connections when release is called

### CODE REVIEW

**Comment by quirinpa** [comment]
Great work!! I'm testing currently.

**Comment by quirinpa** [comment]
It is my great pleasure to announce that Avelino's fix is a huge: **Success!**

I've restored all tests with it in place, and I reached the node tests, and the robot is not in a broken state.

**Review by quirinpa — DISMISSED** [review]

**Review by AlexFernandes-MOVAI — CHANGES_REQUESTED** [review]
please take time to add documentation and maybe a test if not too time consumming

**Comment by quirinpa** [comment]
It's very hard to test currently, @AlexFernandes-MOVAI , since the only way we know how is to run all qa_ui_tests.

**Comment by AlexFernandes-MOVAI** [comment]
> It's very hard to test currently, @AlexFernandes-MOVAI , since the only way we know how is to run all qa_ui_tests.

Not sure, you got the request here, I imagine we can have a pytest which validates our modified class here WSRedisSub does not behave differently than what we expect.

This way we can also instrument the code of this class not to fail silently ...

**Review by andreparames — DISMISSED** [review]
I ran a second session in parallel with the UI tests, and the websocket of that session was unaffected, so the affected connections are those tied only to the original websocket.

**Review by AlexFernandes-MOVAI — APPROVED** [review]

**Comment by quirinpa** [comment]
gg

**Pull request merged**
